spring.application.name=hospital-vm
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_vm?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
logging.level.com.hospital_vm_cl.hospital_vm=DEBUG